#!/usr/bin/perl
#
# SYNTAX:
#	check_opsview_sessions
#
# DESCRIPTION:
#	Returns number of active sessions within last hour in Opsview
#
# AUTHORS:
#	Copyright (C) 2003-2013 Opsview Limited. All rights reserved
#
#    This file is part of Opsview
#
#    Opsview is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    Opsview is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Opsview; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#

use strict;
use FindBin qw($Bin);
use lib "$Bin/../lib", "$Bin/../etc", "$Bin/../perl/lib";
use Opsview::Schema;
use Nagios::Plugin;

my $VERSION = "0.01";

my $np = Nagios::Plugin->new(
    usage     => "Usage: %s",
    shortname => "OPSVIEW-WEB",
    version   => $VERSION,
);

$np->getopts;

my $schema = Opsview::Schema->my_connect;

my $sessions_rs =
  $schema->resultset("Session")->search( { expires => { '>=' => time() }, } );

my $total = $sessions_rs->count;

$np->add_perfdata(
    label => "sessions",
    value => $total,
);

$np->nagios_exit(
    return_code => 0,
    message     => "Active Sessions: $total",
);
