#!/usr/bin/perl
#
#
# AUTHORS:
#       Copyright (C) 2003-2013 Opsview Limited. All rights reserved
#
#    This file is part of Opsview
#
#    Opsview is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    Opsview is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Opsview; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
use strict;
use warnings;

use FindBin qw($Bin);
use lib "/opt/opsview/perl/lib/perl5", "$Bin/../lib";
use Net::SNMP;
use Opsview::NagiosPlugin::SNMP;

my $np = Opsview::NagiosPlugin::SNMP->new(
    usage     => "Usage: %s",
    shortname => "check_snmp_weblogic_deploymentstatus",
    version   => "0.2",
    blurb     => "Checks deployment status of weblogic application servers",
    snmp      => {
        "snmp-version" => 1,
        "snmp-timeout" => 2,
    },
);

$np->add_arg(
    spec => "list|L=s",
    help => qq{-L, --list=INTEGER
    Lists available servers},
);

$np->add_arg(
    spec => "server|S=s",
    help => qq{-S, --server=STRING
    Server name},
);

$np->getopts;

my $list_servers = 0;
my $server_name;

if ( $np->opts->list ) {
    $list_servers = 1;
}
elsif ( $np->opts->server ) {
    $server_name = $np->opts->server;
}
else {
    print "Must specify a server name.\n";
    exit 1;
}

my $s = $np->snmp;

my $oid_testoid            = ".1.3.6.1.4.1.140.625.10.1.0";
my $webServerName_base_oid = ".1.3.6.1.4.1.140.625.430.1.25.32";
my $is_deployed_oid        = ".1.3.6.1.4.1.140.625.430.1.30.32";

my $server_oid;
my $is_deployed;

# Call this when you know you'll get a single value back
sub get_oid_value {
    our ( $oid, $result, $status, $returnstring );

    $oid = shift(@_);

    if ( !defined( $s->get_request($oid) ) ) {
        if ( !defined( $s->get_request($oid_testoid) ) ) {
            $returnstring = "SNMP agent not responding";
            $status       = 1;
            return -1;
        }
        else {
            $returnstring = "SNMP OID does not exist";
            $status       = 1;
            return -1;
        }
    }

    foreach ( $s->var_bind_names() ) {
        $result = $s->var_bind_list()->{$_};
    }

    return $result;
}

if ( !defined( $s->get_request($oid_testoid) ) ) {

    if ( !defined( $s->get_request($oid_testoid) ) ) {
        print "Agent not responding\n";
        exit 1;
    }
}

sub list_all_servers {
    my $name = shift(@_);
    my $key;
    my $results;

    $s->get_table($webServerName_base_oid);
    $results = $s->var_bind_list();

    foreach $key ( keys %$results ) {
        print "$results->{$key}\n";
    }
}

# Finds the sub oid for a particular web server by its name
sub get_suboid_by_name {
    my $name = shift(@_);
    my $key;
    my $results;

    $s->get_table($webServerName_base_oid);
    $results = $s->var_bind_list();

    foreach $key ( keys %$results ) {
        if ( $results->{$key} =~ /^$name$/ ) {
            $key =~ s/^$webServerName_base_oid//;
            return $key;
        }
    }

    # Couldn't find name -> undef
}

# Listing servers is not a normal plugin operation so we just
# display the list and quit.  This is for troubleshooting/setup
# only
if ($list_servers) {
    list_all_servers();
    exit 0;
}

# Get the sub OID for this particular server
$server_oid = get_suboid_by_name($server_name);

if ( $server_oid eq "" ) {
    print "Couldn't find specified server\n";
    exit 1;
}

$is_deployed = get_oid_value( "$is_deployed_oid$server_oid" );

# Show appropriate message (we don't have a critical state)
if ( $is_deployed =~ /^deployed$/i ) {
    print "OK - server $server_name is in state $is_deployed.\n";
    exit 0;
}
elsif ( $is_deployed =~ /^notdeployed$/i ) {
    print "CRITICAL - server $server_name is in state $is_deployed.\n";
    exit 2;
}
else {
    print "UNKNOWN - Response '$is_deployed' not recognised.\n";
    exit 3;
}
