#!/usr/bin/perl
#
# AUTHORS:
#	Copyright (C) 2003-2013 Opsview Limited. All rights reserved
#
#    This file is part of Opsview
#
#    Opsview is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    Opsview is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Opsview; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#

use lib qw ( /usr/local/nagios/perl/lib );
use Net::SNMP;
use Getopt::Std;

$script             = "check_snmp_netscaler_clientconnections";
$script             = $EXECUTABLE_NAME;
$script_version     = "1.0";
$script_description = "Generic script for monitoring numeric SNMP OID value";

$oid_sysDescr          = ".1.3.6.1.2.1.1.1.0";
$oid_requiredparameter = ".1.3.6.1.4.1.5951.1.2.1.2.0";

$ipaddress    = "192.168.1.1"; # Default IP address
$version      = "1";           # SNMP version
$community    = "public";      # Default community string
$timeout      = 10;            # Response timeout (seconds)
$warning      = 80;            # Default warning threshold
$critical     = 90;            # Default critical threshold
$status       = 0;
$returnstring = "";
my $port = 161;

# Do we have enough information?
if ( @ARGV < 1 ) {
    print "Too few arguments\n";
    usage();
}

getopts( "hH:C:w:c:p:" );
if ($opt_h) {
    usage();
    exit(0);
}
if ($opt_H) {
    $hostname = $opt_H;

    # print "Hostname $opt_H\n";
}
else {
    print "No hostname specified\n";
    usage();
}
if ($opt_C) {
    $defaultcommunity = $opt_C;

    # print "Using community $opt_C\n";
}
else {

    # print "Using community $community\n";
}
if ($opt_w) {
    $warning = $opt_w;

    # print "Warning threshold: $opt_w%\n";
}
if ($opt_c) {
    $critical = $opt_c;

    # print "Critical threshold: $opt_c%\n";
}
if ($opt_p) {
    $port = $opt_p;
}

# Create the SNMP session
my ( $s, $e ) = Net::SNMP->session(
    -community => return_snmpcommunity($hostname),
    -hostname  => $hostname,
    -version   => $version,
    -timeout   => $timeout,
    -port      => $port,
);

main();

# Close the session
$s->close();

if ( $returnstring eq "" ) {
    $status = 3;
}

if ( $status == 0 ) {
    print "Status is OK - $returnstring\n";

    # print "$returnstring\n";
}
elsif ( $status == 1 ) {
    print "Status is a WARNING level - $returnstring\n";
}
elsif ( $status == 2 ) {
    print "Status is CRITICAL - $returnstring\n";
}
else {
    print "Status is UNKNOWN\n";
}

exit $status;

####################################################################
# This is where we gather data via SNMP and return results         #
####################################################################

sub main {

    if ( !defined( $s->get_request($oid_requiredparameter) ) ) {
        if ( !defined( $s->get_request($oid_sysDescr) ) ) {
            $returnstring = "SNMP agent not responding";
            $status       = 1;
            return 1;
        }
        else {
            $returnstring = "SNMP OID does not exist";
            $status       = 1;
            return 1;
        }
    }
    foreach ( $s->var_bind_names() ) {
        $requiredparameter = $s->var_bind_list()->{$_};
    }

    if ( $requiredparameter >= $critical ) {
        $status = 2;
    }
    elsif ( $requiredparameter >= $warning ) {
        $status = 1;
    }

    $temp = "Parameter: $requiredparameter|parameter=$requiredparameter";

    append($temp);
}

####################################################################
# help and usage information                                       #
####################################################################

sub usage {
    print << "USAGE";
--------------------------------------------------------------------	 
$script v$script_version

$script_description

Usage: $script -H <hostname> -c <community> [...]
Options: -H 		Hostname or IP address
         -p 		Port (default: 161)
         -C 		Community (default is public)
         -w 		Warning threshold (as %)
         -c 		Critical threshold (as %)
	 
--------------------------------------------------------------------	 
Copyright (C) 2003-2013 Opsview Limited. All rights reserved	 

$script comes with absolutely NO WARRANTY either implied or explicit
This program is licensed under the terms of the GNU General Public 
License (check source code for details)
--------------------------------------------------------------------

USAGE
    exit 1;
}

####################################################################
# Appends string to existing $returnstring                         #
####################################################################

sub append {
    my $appendstring = @_[0];
    $returnstring = "$returnstring$appendstring";
}
