#!/usr/bin/perl
#
#
# AUTHORS:
#	Copyright (C) 2003-2013 Opsview Limited. All rights reserved
#
#    This file is part of Opsview
#
#    Opsview is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    Opsview is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Opsview; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
use warnings;
use strict;

use FindBin qw($Bin);
use lib "/opt/opsview/perl/lib/perl5", "$Bin/../lib";
use Net::SNMP;
use Opsview::NagiosPlugin::SNMP;

my $np = Opsview::NagiosPlugin::SNMP->new(
    usage     => "Usage: %s",
    shortname => "check_snmp_cisco_ha",
    version   => "2.1.1",
    blurb     => "Whether the Cisco PIX in HA mode is master",
    snmp      => {
        "snmp-version" => 1,
        "snmp-timeout" => 2,
    },
);

$np->getopts;

my $s            = $np->snmp;
my $oid_sysDescr = ".1.3.6.1.2.1.1.1.0";
my $oid_IsMaster = ".1.3.6.1.4.1.9.9.147.1.2.1.1.1.3.6";
my $status       = 0;
my $returnstring = "";

main();

# Close the session
$s->close();

if ( $returnstring eq "" ) {
    $status = 3;
}

if ( $status == 0 ) {
    print "Status is OK - $returnstring\n";

    # print "$returnstring\n";
}
elsif ( $status == 1 ) {
    print "Status is a WARNING level - $returnstring\n";
}
elsif ( $status == 2 ) {
    print "Status is CRITICAL - $returnstring\n";
}
else {
    print "Status is UNKNOWN\n";
}

exit $status;

####################################################################
# This is where we gather data via SNMP and return results         #
####################################################################

sub main {

    if ( !defined( $s->get_request($oid_IsMaster) ) ) {
        if ( !defined( $s->get_request($oid_sysDescr) ) ) {
            $returnstring = "SNMP agent not responding";
            $status       = 1;
            return 1;
        }
        else {
            $returnstring = "SNMP OID does not exist";
            $status       = 1;
            return 1;
        }
    }
    my $ismaster      = 0;
    my $text_ismaster = "";
    foreach ( $s->var_bind_names() ) {
        $ismaster = $s->var_bind_list()->{$_};
    }

    if ( $ismaster eq "9" ) {
        my $reason = failurereason($ismaster);
        $text_ismaster = "Running as master ($reason)\n";
        $status        = 0;
    }
    else {
        my $reason = failurereason($ismaster);
        $text_ismaster = "NOT running as master, reason: $reason\n";
        $status        = 2;
    }

    append($text_ismaster);

}
####################################################################
# Appends string to existing $returnstring                         #
####################################################################

sub append {
    my $appendstring = $_[0];
    $returnstring = "$returnstring$appendstring";
}

sub failurereason {
    my $value        = $_[0];
    my $returnstring = "";

    if ( $value eq "1" ) {
        $returnstring = "other";
    }
    elsif ( $value eq "2" ) {
        $returnstring = "up";
    }
    elsif ( $value eq "3" ) {
        $returnstring = "down";
    }
    elsif ( $value eq "4" ) {
        $returnstring = "error";
    }
    elsif ( $value eq "5" ) {
        $returnstring = "over temp";
    }
    elsif ( $value eq "6" ) {
        $returnstring = "busy";
    }
    elsif ( $value eq "7" ) {
        $returnstring = "no media";
    }
    elsif ( $value eq "8" ) {
        $returnstring = "backup";
    }
    elsif ( $value eq "9" ) {
        $returnstring = "active";
    }
    elsif ( $value eq "10" ) {
        $returnstring = "standby";
    }
    else {
        $returnstring = "unknown";
    }
    return ($returnstring);
}
