#!/usr/bin/perl
#
#
# AUTHORS:
#       Copyright (C) 2003-2013 Opsview Limited. All rights reserved
#
#    This file is part of Opsview
#
#    Opsview is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    Opsview is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Opsview; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
use strict;
use warnings;

use FindBin qw($Bin);
use lib "/opt/opsview/perl/lib/perl5", "$Bin/../lib";
use Net::SNMP;
use Opsview::NagiosPlugin::SNMP;

my $np = Opsview::NagiosPlugin::SNMP->new(
    usage     => "Usage: %s",
    shortname => "check_snmp_weblogic_jms_server",
    version   => "1.1",
    blurb     => "Checks number of JMS servers or current connection count",
    snmp      => {
        "snmp-version" => 1,
        "snmp-timeout" => 2,
    },
);

$np->add_arg(
    spec => "warning|w=s",
    help => qq{-w, --warning=INTEGER
    Warning threshold},
    required => 1,
);

$np->add_arg(
    spec => "critical|c=s",
    help => qq{-c, --critical=INTEGER
    Critical threshold},
    required => 1,
);

$np->add_arg(
    spec => "connections|O=s",
    help => qq{-O, --connections=INTEGER
    Current connection count},
);

$np->add_arg(
    spec => "server|S=s",
    help => qq{-S, --server=INTEGER
    JMS server count},
);

$np->getopts;

my $check_servers;
if ( $np->opts->connections ) {
    $check_servers = 0;
}
elsif ( $np->opts->server ) {
    $check_servers = 1;
}
else {
    print "Must specify one of -S or -O\n";
    exit 3;
}

my $warning  = $np->opts->warning;
my $critical = $np->opts->critical;

my $s = $np->snmp;

my $oid_testoid     = ".1.3.6.1.4.1.140.625.10.1.0";
my $oid_jms_servers = ".1.3.6.1.4.1.140.625.240.1.50";
my $oid_jms_conns   = ".1.3.6.1.4.1.140.625.240.1.30";

my $count    = 0;
my $retmsg   = "";
my $perfdata = "";

# Call this when you know you'll get a single value back
sub get_oid_value {
    our ( $oid, $result, $status, $returnstring );

    $oid = shift(@_);

    if ( !defined( $s->get_next_request($oid) ) ) {
        if ( !defined( $s->get_request($oid_testoid) ) ) {
            $returnstring = "SNMP agent not responding";
            $status       = 1;
            return -1;
        }
        else {
            $returnstring = "SNMP OID does not exist";
            $status       = 1;
            return -1;
        }
    }

    foreach ( $s->var_bind_names() ) {
        $result = $s->var_bind_list()->{$_};
        if ( $_ !~ /^$oid/ ) {
            print "UNKNOWN - OID does not exist!\n";
            exit 3;
        }
    }

    return $result;
}
if ( !defined( $s->get_request($oid_testoid) ) ) {
    if ( !defined( $s->get_request($oid_testoid) ) ) {
        print "Agent not responding\n";
        exit 1;
    }
}

# We either check servers or connections
if ( $check_servers eq 1 ) {
    $count = get_oid_value($oid_jms_servers);

    if ( $count eq -1 ) {
        print "UNKNOWN - Plugin error, couldn't retrieve OID\n";
        exit 3;
    }

    # Output text
    $retmsg = "$count JMS servers running";

    # Performance data
    $perfdata = "servers=$count";
}
else {
    $count = get_oid_value($oid_jms_conns);

    if ( $count eq -1 ) {
        print "UNKNOWN - Plugin error, couldn't retrieve OID\n";
        exit 3;
    }

    # Output text
    $retmsg = "$count current connections";

    # Performance data
    $perfdata = "connections=$count";
}

# Show appropriate message (we don't have a critical state)
if ( $count > $critical ) {
    print "CRITICAL - $retmsg |$perfdata\n";
    exit 2;
}
elsif ( $count > $warning ) {
    print "WARNING - $retmsg |$perfdata\n";
    exit 1;
}
else {
    print "OK - $retmsg |$perfdata\n";
    exit 0;
}
