#!/usr/bin/perl

#    Copyright (C) 2003-2013 Opsview Limited. All rights reserved
#
#    This file is part of Opsview
#
#    Opsview is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    Opsview is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Opsview; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#

use strict;
use Getopt::Std;
use FindBin qw($Bin);

my $script = 'check_opsview_master';

my $opts = {};

getopts( "h", $opts );
if ( $opts->{h} ) {
    usage();
    exit(0);
}

my $output = `$Bin/check_tcp -H /usr/local/nagios/var/rw/opsviewd.cmd`;
my $rc     = ( $? >> 8 );
if ( $rc != 0 ) {
    print "opsviewd error: $output";
    exit 2;
}
print $output;
exit $rc;

####################################################################
# help and usage information                                       #
####################################################################

sub usage {
    print << "USAGE";
--------------------------------------------------------------------	 
$script

Returns status of Opsview master server

--------------------------------------------------------------------	 
Copyright (C) 2003-2013 Opsview Limited. All rights reserved	 
	 
This program is free software; you can redistribute it or modify
it under the terms of the GNU General Public License
--------------------------------------------------------------------
	 
USAGE
    exit 1;
}
