#!/usr/bin/perl
#
# AUTHORS:
#       Copyright (C) 2003-2013 Opsview Limited. All rights reserved
#
#    This file is part of Opsview
#
#    Opsview is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    Opsview is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Opsview; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
use strict;
use warnings;

use FindBin qw($Bin);
use lib "/opt/opsview/perl/lib/perl5", "$Bin/../lib";
use Net::SNMP;
use Opsview::NagiosPlugin::SNMP;

my $np = Opsview::NagiosPlugin::SNMP->new(
    usage     => "Usage: %s",
    shortname => "check_snmp_weblogic_clusterservers",
    version   => "1.1",
    blurb => "Checks the number of cluster servers - either active or total",
    snmp  => {
        "snmp-version" => 1,
        "snmp-timeout" => 2,
    },
);

$np->add_arg(
    spec => "warning|w=s",
    help => qq{-w, --warning=INTEGER
    Warning threshold (minimum)},
    required => 1,
);

$np->add_arg(
    spec => "critical|c=s",
    help => qq{-c, --critical=INTEGER
    Critical threshold (minimum)},
    required => 1,
);

$np->add_arg(
    spec => "server|s=s",
    help => qq{-s, --servername=INTEGER
    Server name},
);

$np->add_arg(
    spec => "servers|S=s",
    help => qq{-S, --servers=INTEGER
    Servers in cluster},
);

$np->add_arg(
    spec => "activeservers|A=s",
    help => qq{-A, --activeservers=INTEGER
    Active servers},
);

$np->getopts;

my $warning  = $np->opts->warning;
my $critical = $np->opts->critical;
my $check_total;

#check required options being used
if ( $np->opts->servers ) {
    $check_total = 1;
}
elsif ( $np->opts->activeservers ) {
    $check_total = 0;
}
else {
    print "Must specify either -S or -A\n";
    exit 3;
}

my $s = $np->snmp;

my $oid_testoid       = ".1.3.6.1.4.1.140.625.10.1.0";
my $oid_totalservers  = ".1.3.6.1.4.1.140.625.110.1.50";
my $oid_activeservers = ".1.3.6.1.4.1.140.625.110.1.25";

my $count    = 0;
my $retmsg   = "";
my $perfdata = "";

# Call this when you know you'll get a single value back
sub get_oid_value {
    our ( $oid, $result, $status, $returnstring );

    $oid = shift(@_);

    if ( !defined( $s->get_next_request($oid) ) ) {
        if ( !defined( $s->get_request($oid_testoid) ) ) {
            $returnstring = "SNMP agent not responding\n";
            $status       = 1;
            return -1;
        }
        else {
            $returnstring = "SNMP OID does not exist";
            $status       = 1;
            return -1;
        }
    }

    foreach ( $s->var_bind_names() ) {
        $result = $s->var_bind_list()->{$_};
        if ( $_ !~ /^$oid/ ) {
            print "UNKNOWN - OID does not exist!\n";
            exit 3;
        }
    }

    return $result;
}

if ( !defined( $s->get_request($oid_testoid) ) ) {
    if ( !defined( $s->get_request($oid_testoid) ) ) {
        print "Agent not responding\n";
        exit 1;
    }
}

# We either check servers or connections
if ( $check_total eq 1 ) {
    my $serverlist = get_oid_value($oid_totalservers);

    my @count = split( /,/, $serverlist );
    $count = @count;

    if ( $count eq -1 ) {
        print "UNKNOWN - Plugin error, couldn't retrieve OID\n";
        exit 3;
    }

    # Output text
    $retmsg = "$count servers are in this cluster";

    # Performance data
    $perfdata = "total_servers=$count;$warning;$critical;";
}
else {
    $count = get_oid_value($oid_activeservers);

    if ( $count eq -1 ) {
        print "UNKNOWN - Plugin error, couldn't retrieve OID\n";
        exit 3;
    }

    # Output text
    $retmsg = "$count currently active servers";

    # Performance data
    $perfdata = "active_servers=$count;$warning;$critical;";
}

# Show appropriate message (we don't have a critical state)
if ( $count < $critical ) {
    print "CRITICAL - $retmsg |$perfdata\n";
    exit 2;
}
elsif ( $count < $warning ) {
    print "WARNING - $retmsg |$perfdata\n";
    exit 1;
}
else {
    print "OK - $retmsg |$perfdata\n";
    exit 0;
}
