#!/usr/bin/perl
#
#
# AUTHORS:
#	Copyright (C) 2003-2013 Opsview Limited. All rights reserved
#
#    This file is part of Opsview
#
#    Opsview is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    Opsview is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Opsview; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
use warnings;
use strict;

use FindBin qw($Bin);
use lib "/opt/opsview/perl/lib/perl5", "$Bin/../lib";
use Net::SNMP;
use Opsview::NagiosPlugin::SNMP;

my $np = Opsview::NagiosPlugin::SNMP->new(
    usage     => "Usage: %s",
    shortname => "check_snmp_cisco_bgppeer",
    version   => "2.1.1",
    blurb     => "Checks the status of a Cisco BGP peer.",
    snmp      => {
        "snmp-version" => 1,
        "snmp-timeout" => 2,
    },
);

$np->add_arg(
    spec => "i=s",
    help => qq{-i=INTEGER
	Peer IP address to be checked},
    default => "",
);

$np->getopts;

my $peerip                 = $np->opts->i;
my $oid_sysDescr           = ".1.3.6.1.2.1.1.1.0";
my $oid_bgpPeerAdminStatus = ".1.3.6.1.2.1.15.3.1.2";

my $returnstring = "";
my $status       = 0;

my $s = $np->snmp;

main();

# Close the session
$s->close();

if ( $returnstring eq "" ) {
    $status = 3;
}

if ( $status == 0 ) {
    print "Status is OK - $returnstring\n";
}
elsif ( $status == 1 ) {
    print "Status is a WARNING level - $returnstring\n";
}
elsif ( $status == 2 ) {
    print "Status is CRITICAL - $returnstring\n";
}
else {
    print "Status is UNKNOWN\n";
}

exit $status;

####################################################################
# This is where we gather data via SNMP and return results         #
####################################################################

sub main {

    my $oid_temp = $oid_bgpPeerAdminStatus . "." . $peerip;
    if ( !defined( $s->get_request($oid_temp) ) ) {
        if ( !defined( $s->get_request($oid_sysDescr) ) ) {
            $returnstring = "SNMP agent not responding";
            $status       = 1;
            return 1;
        }
        else {
            $returnstring = "BGP Peer OID does not exist";
            $status       = 1;
            return 1;
        }
    }
    my $bgpPeerAdminStatus = "";
    my $text_bgppeer;
    foreach ( $s->var_bind_names() ) {
        $bgpPeerAdminStatus = $s->var_bind_list()->{$_};
    }

    if ( $bgpPeerAdminStatus eq "6" ) {
        my $reason = failurereason($bgpPeerAdminStatus);
        $text_bgppeer = "BGP peer session with $peerip state OK ($reason)\n";
        $status       = 0;
    }
    else {
        my $reason = failurereason($bgpPeerAdminStatus);
        $text_bgppeer =
          "BGP peer session with $peerip ERROR! reason: $reason\n";
        $status = 2;
    }

    append($text_bgppeer);

}
####################################################################
# Appends string to existing $returnstring                         #
####################################################################

sub append {
    my $appendstring = $_[0];
    $returnstring = "$returnstring$appendstring";
}

sub failurereason {
    my $value        = $_[0];
    my $returnstring = "";

    if ( $value eq "1" ) {
        $returnstring = "idle";
    }
    elsif ( $value eq "2" ) {
        $returnstring = "connect";
    }
    elsif ( $value eq "3" ) {
        $returnstring = "active";
    }
    elsif ( $value eq "4" ) {
        $returnstring = "opennet";
    }
    elsif ( $value eq "5" ) {
        $returnstring = "openconfirm";
    }
    elsif ( $value eq "6" ) {
        $returnstring = "established";
    }
    else {
        $returnstring = "unknown";
    }
    return ($returnstring);
}
