#!/usr/bin/perl
#
#
# SYNTAX:
#	examine_orig_traps {hostname}
#
# DESCRIPTION:
#	Returns all traps from /usr/local/nagios/var/traps.db for specified hostname
#	Prints trap contents to stdout
#
# AUTHORS:
#	Copyright (C) 2003-2013 Opsview Limited. All rights reserved
#
#    This file is part of Opsview
#
#    Opsview is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    Opsview is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Opsview; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#

use strict;
use FindBin qw($Bin);
use lib "/usr/local/nagios/perl/lib";
use DBI;

my $hostname = shift @ARGV or die "No hostname specified";
my $db = "/usr/local/nagios/var/traps.db";

# No traps saved - exit
exit 0 unless ( -e $db );

my $dbh = DBI->connect( "dbi:SQLite:dbname=$db" );

my $sth =
  $dbh->prepare( "SELECT unixtime,trap FROM tracing WHERE hostname=?" );
$sth->execute($hostname);
while ( my ( $time, $trap ) = $sth->fetchrow_array ) {
    print "Time: ", scalar( localtime($time) ), " - ";
    $trap =~ m/^SNMPv2-MIB::snmpTrapOID.0 (.*)$/m;
    my $name = $1;
    print $name, $/;
}
