#!/usr/bin/perl
#
# Copyright (C) 2003-2013 Opsview Limited. All rights reserved
#
# This is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Opsview; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

use warnings;
use strict;
use lib "/usr/local/nagios/perl/lib";
use Cache::FastMmap;

my $cache =
  Cache::FastMmap->new( share_file => "/tmp/opsview/web/session_data" );
my @a = $cache->get_keys(2);

my $one_hour_ago = time() - 3600;
my $sessions;
my @last_hour = grep {
         $_->{key} =~ /^session:/
      && $_->{last_access} >= $one_hour_ago
      && ++$sessions->{ $_->{value}->{__user} }
} @a;

print "Sessions in the last hour: ", scalar @last_hour, $/;
print "Sessions per user:", $/;
foreach $_ ( keys %$sessions ) {
    print " $_: ", $sessions->{$_}, $/;
}
