#!/usr/bin/perl
#
# Small script to reschedule all host checks
#
# AUTHORS:
#   Copyright (C) 2003-2013 Opsview Limited. All rights reserved
#
#    This file is part of Opsview
#
#    Opsview is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    Opsview is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Opsview; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#

use strict;
use warnings;

use lib '/usr/local/nagios/perl/lib';
use lib '/usr/local/nagios/lib';

use Opsview;
use Opsview::Host;

my $cmdfile = '/usr/local/nagios/var/rw/nagios.cmd';

if ( !-p $cmdfile ) {
    die 'Command file not found - is Opsview running?', $/;
}

my $host_list = Opsview::Host->retrieve_all;

open( my $cmdfile_fh, '>', $cmdfile )
  || die( "Unable to open $cmdfile for writing: $!$/" );

while ( my $host = $host_list->next ) {
    print {$cmdfile_fh} '[', time, '] SCHEDULE_HOST_CHECK;', $host->name, ';',
      time, $/;
}

close($cmdfile_fh) || die( "Unable to close $cmdfile: $!$/" );
