#!/usr/bin/perl
# Quick script to clean up a demo vm before publishing
#
# AUTHORS:
#	Copyright (C) 2003-2013 Opsview Limited. All rights reserved
#
#    This file is part of Opsview
#
#    Opsview is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    Opsview is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Opsview; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#

use strict;
use FindBin qw($Bin);
use lib "$Bin", "$Bin/../lib", "$Bin/../etc", "$Bin/../perl/lib";
use Opsview;
use Runtime;
use File::Slurp;

my $dbh = Opsview->db_Main;
$dbh->do(
    "UPDATE systempreferences SET uuid='', opsview_server_name='', enable_odw_import=0"
);
$dbh->do( "UPDATE contacts SET show_welcome_page=1" );

my $runtime = Runtime->db_Main;
$runtime->do( "TRUNCATE nagios_servicechecks" );

my $opsview_build_os          = "$Bin/../etc/opsview_build_os";
my $opsview_build_os_contents = read_file( "$Bin/../etc/opsview_build_os" );

if ( $opsview_build_os_contents !~ /^[-\w]+\(demovm|ec2\)/ ) {
    die 'ERROR: "(demovm) or (ec2)" missing from opsview_build_os', $/;
}
