#!/bin/sh
# 
#
# preremove script
#
#	Run as nagios user.
#
# AUTHORS:
#	Copyright (C) 2003-2013 Opsview Limited. All rights reserved
#
#    This file is part of Opsview
#
#    Opsview is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    Opsview is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Opsview; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#


die() { echo $1; exit 1; }

tmpfile=/usr/local/nagios/tmp/opsview-preremove.$$

echo "Removing Nagios crontab entries"
rm -f $tmpfile
crontab -l | perl -ne '$start=1 if (/^# OPSVIEW-START/); print $_ unless ($start); $start=0 if (/^# OPSVIEW-END/)' > $tmpfile
crontab $tmpfile || die "Could not create nagios' crontab"
rm -f $tmpfile
